version: "3.9"

services:
  db:
    image: postgres:16
    container_name: poolforyou-db
    environment:
      POSTGRES_DB: poolforyou
      POSTGRES_USER: poolforyou_user
      POSTGRES_PASSWORD: poolforyou_pass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
